import type { CampaignEventCard } from './types.js';

// Nyhetshandelser i valrorelsen 2026. Varje vecka vands ett kort som gor en
// sakfraga "het". Kriser (crisis: true) drabbar dessutom ett lag, som da
// maste valja hur det bemoter skandalen.

export const CAMPAIGN_EVENTS: CampaignEventCard[] = [
  {
    id: 'ev_skjutning',
    title: 'Ny vag av gangskjutningar',
    body: 'Flera skjutningar i storstaderna pa en helg. Tryggheten dominerar nyhetsflodet.',
    hotIssue: 'brott',
    crisis: false,
    source: 'Brottsforebyggande radet',
  },
  {
    id: 'ev_elpris',
    title: 'Elpriserna rasar i hojden',
    body: 'En kall vinter och stoppad reaktor far elpriset att sla rekord.',
    hotIssue: 'energi',
    crisis: false,
    regionShift: { region: 'norr', party: 's', amount: 4 },
    source: 'Svenska kraftnat',
  },
  {
    id: 'ev_nato',
    title: 'Spant lage i Ostersjon',
    body: 'Okad militar aktivitet far forsvarsfragan i fokus.',
    hotIssue: 'forsvar',
    crisis: false,
    source: 'Forsvarsmakten',
  },
  {
    id: 'ev_vardkris',
    title: 'Rekordlanga vardkoer',
    body: 'Nya siffror visar att vardkoerna aldrig varit langre.',
    hotIssue: 'valfard',
    crisis: false,
    source: 'Socialstyrelsen',
  },
  {
    id: 'ev_skolresultat',
    title: 'Svenska skolresultat faller',
    body: 'En internationell matning visar sjunkande kunskaper.',
    hotIssue: 'skola',
    crisis: false,
    source: 'Skolverket',
  },
  {
    id: 'ev_inflation',
    title: 'Hushallen pressas av inflationen',
    body: 'Matpriser och rantor biter. Planbokens fragor tar over debatten.',
    hotIssue: 'ekonomi',
    crisis: false,
    source: 'Konjunkturinstitutet',
  },
  {
    id: 'ev_almedalen',
    title: 'Almedalsveckan',
    body: 'Partiledarna samlas i Visby. Allt fokus pa politiska utspel.',
    hotIssue: 'valfard',
    crisis: false,
    regionShift: { region: 'gotland', party: 'c', amount: 6 },
    source: 'Almedalsveckan',
  },
  {
    id: 'ev_klimattoppmote',
    title: 'FN:s klimattoppmote',
    body: 'Larmrapporter far miljofragan att klattra pa dagordningen.',
    hotIssue: 'klimat',
    crisis: false,
    regionShift: { region: 'storstad', party: 'mp', amount: 5 },
    source: 'FN:s klimatpanel',
  },
  {
    id: 'ev_reaktor',
    title: 'Industribesked om ny karnkraft',
    body: 'Ett besked om nya reaktorer satter energipolitiken hogst pa agendan.',
    hotIssue: 'energi',
    crisis: false,
    source: 'Vattenfall',
  },
  {
    id: 'ev_slutdebatt',
    title: 'Den stora slutdebatten',
    body: 'Partiledarna mots i tv:s slutdebatt infor valdagen.',
    hotIssue: 'valfard',
    crisis: false,
    source: 'SVT/TV4',
  },
  // --- Kriser ---------------------------------------------------------------
  {
    id: 'cr_drev',
    title: 'Mediedrev mot partitopp',
    body: 'En avslojning skakar ett av partierna. Fortroendet star pa spel.',
    hotIssue: 'brott',
    crisis: true,
    source: 'Granskande journalistik',
  },
  {
    id: 'cr_sms',
    title: 'Lackta sms satter parti i blasvader',
    body: 'Interna meddelanden har lackt till pressen. Ett lag tvingas forklara sig.',
    hotIssue: 'ekonomi',
    crisis: true,
    source: 'Kvallspressen',
  },
  {
    id: 'cr_avhopp',
    title: 'Tungt avhopp mitt i kampanjen',
    body: 'En toppkandidat lamnar sitt parti i protest. Kaos utbryter.',
    hotIssue: 'migration',
    crisis: true,
    source: 'TT Nyhetsbyran',
  },
  {
    id: 'cr_faktagranskning',
    title: 'Faktagranskning slar ner pa loften',
    body: 'Ett partis vallofte sagas som orealistiskt av experterna.',
    hotIssue: 'skola',
    crisis: true,
    source: 'Faktakollen',
  },
];
